title: SketchUp Extension FAQ
# theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Hide "View on GitHub" link.
# https://github.com/pages-themes/cayman/issues/29#issuecomment-339016299
github:
  is_project_page: false
